#!/bin/sh
awk '
BEGIN {
        RS=""
        FS="\n"
        OFS=" "
}
{
        for(i=1;i<NF;++i){
                max=-1
                min=99
                sum=0
                avg-0
                split($i,r,"\",\"")
                count=0;
                for(j=5;j<61;j++){
                        if (r[j]>max) { max=r[j] }
                        if (r[j]<min) { min=r[j] }
                        sum+=r[j]
                        if (r[j]>0) { count++ }
                }
                if (count!=0) { avg=sum/count }
                if (max==-1) { max="-nan" }
                if (min==99) { min="-nan" }
                if (avg==0) { avg="-nan" }
                print r[2], count,sum,avg,min,max
        }
}' API_SI.POV.GINI_DS2_en_csv_v2.csv
